services:
  pg:
    image: bitnami/postgresql:latest
    ports:
      - "5482:5482"
    env_file:
      - .env

    volumes:
      - pg_data:/bitnami/postgresql
      - ./docker:/docker-entrypoint-initdb.d
      
volumes:
  pg_data: