_format_version: "3.0"

services:
  - name: orders
    url: http://host.docker.internal:3333
    routes:
      - name: api-orders
        protocols:
          - http
          - https 
        paths:
          - /orders

  - name: invoices
    url: http://host.docker.internal:3334
    routes:
      - name: api-invoices
        protocols:
          - http
          - https 
        paths:
          - /invoices

plugins:
  - name: cors
    config: 
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - DELETE  # <-- CORRIGIDO
        - PATCH
      headers:
        - Accept
        - Content-Type
        - Authorization